node{
    properties([pipelineTriggers([githubPush()])])

    step([$class: 'WsCleanup'])

    stage('Checkout') {
        checkout(
            $class: 'GitSCM',
            branches: [[name: '*/master']],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'CloneOption', depth: 1, noTags: true, reference: '', shallow: true]
            ],
            submoduleCfg: [],
            userRemoteConfigs: [[url: 'https://code.aliyun.com/oocl-training/grow-service.git']]
        )
    }

    stage('Test') {
        sh './gradlew test'
    }

    stage('Build') {
        sh './gradlew build'
    }

    withEnv(['IMAGE_REGISTRY=registry-vpc.cn-shenzhen.aliyuncs.com/agile-training',
                 'IMAGE_REPO=grow-service']) {

        stage('GenImage') {
            sh 'bash ./ci/genImage.sh'
        }
    }
}