node{
    step([$class: 'WsCleanup'])

    stage('Checkout') {
        git url: 'https://github.com/seabornlee/grow.git', branch: 'master'
    }

    stage('Test') {
        sh './gradlew test'
    }

    stage('Build') {
        sh './gradlew build'
    }
}